### ISSUE TITLE
this stuff is hard ,where is the script to control the attack ?

### ISSUE THREAD

**Issue by stickylabdev** [BruceLouis/2D-Fighting-Game-Project#1]
where is the script to control the attack ?
I DONT KNOW HOW TO LAUNCH SPECIAL ATTACK ,I MEAN THIS SYMBOL ↘️ I,,WHAT SHOULD I CLICK ON MY LAPPTOP , ?.

KEN:

⬇️↘️➡️ + punch for hadouken

➡️⬇️↘️ + punch for shoryuken

⬇️↙️⬅️ + kick for hurricane kick

⬇️↘️➡️ + kick for roll

⬇️↘️➡️ ⬇️↘️➡️ + punch for super

FEI LONG:

⬇️↘️➡️ + punch for rekka

➡️⬇️↘️ + kick for chicken wing

⬅️⬇️↙️ + kick for flame kick

⬇️↘️➡️ ⬇️↘️➡️ + punch for super

BALROG:

⬅️ hold ➡️ + punch for dash straight

⬅️ hold ↘️ + punch for dash low

⬅️ hold ➡️ + kick for kick rush

⬇️ hold ⬆️️ + punch for headbutt

⬇️↘️➡️ ⬇️↘️➡️ + punch for super

AKUMA:

⬇️↘️➡️ + punch for hadouken (can be done in the air as well)

➡️⬇️↘️ + punch for shoryuken

⬇️↙️⬅️ + kick for hurricane kick

➡️⬇️↘️ + kick for demon flip ( punch for palm, kick for divekick, nothing for slide)

A A ➡️ Z D + full super bar for raging demon

SAGAT:

⬇️↘️➡️ + punch for high tiger shot

⬇️↘️➡️ + kick for low tiger shot

➡️⬇️↘️ + punch for tiger uppercut

➡️⬇️↘️ + kick for tiger knee

⬇️↘️➡️ ⬇️↘️➡️ + punch for super

**Comment by BruceLouis** [comment]
↘️ you click down and forward together

and its under ComboSystem.cs if you wanna make it easier for yourself.

**Comment by stickylabdev** [comment]
maybe that is impossiblle :'(,, i will look forward ,thanks

**Comment by stickylabdev** [comment]
if you can make some tutorial about how to do it , it would be amazing , till now i can not do a combo , or special skills ,,, even after you explain what ↘️ is ,, :'( it so hard

**Comment by BruceLouis** [comment]
https://www.youtube.com/watch?v=gaEeKCImkG8 this could be a good starting point

**Comment by stickylabdev** [comment]
no , i still can't do it on your project , creeply cried :'(

**Comment by BruceLouis** [comment]
you want to be able to execute the hadouken command or you want to change something in the script so it'll be easier?

**Comment by stickylabdev** [comment]
i want to do both of you said

**Comment by stickylabdev** [comment]
i still can not do this stufff on using my keyboard ,i really try it for a manytimes but still failed ,,, :'(


KEN:

⬇️↘️➡️ + punch for hadouken

➡️⬇️↘️ + punch for shoryuken

⬇️↙️⬅️ + kick for hurricane kick

⬇️↘️➡️ + kick for roll

⬇️↘️➡️ ⬇️↘️➡️ + punch for super

FEI LONG:

⬇️↘️➡️ + punch for rekka

➡️⬇️↘️ + kick for chicken wing

⬅️⬇️↙️ + kick for flame kick

⬇️↘️➡️ ⬇️↘️➡️ + punch for super

BALROG:

⬅️ hold ➡️ + punch for dash straight

⬅️ hold ↘️ + punch for dash low

⬅️ hold ➡️ + kick for kick rush

⬇️ hold ⬆️️ + punch for headbutt

⬇️↘️➡️ ⬇️↘️➡️ + punch for super

AKUMA:

⬇️↘️➡️ + punch for hadouken (can be done in the air as well)

➡️⬇️↘️ + punch for shoryuken

⬇️↙️⬅️ + kick for hurricane kick

➡️⬇️↘️ + kick for demon flip ( punch for palm, kick for divekick, nothing for slide)

A A ➡️ Z D + full super bar for raging demon

SAGAT:

⬇️↘️➡️ + punch for high tiger shot

⬇️↘️➡️ + kick for low tiger shot

➡️⬇️↘️ + punch for tiger uppercut

➡️⬇️↘️ + kick for tiger knee

⬇️↘️➡️ ⬇️↘️➡️ + punch for super

**Comment by BruceLouis** [comment]
if you look at the PunchBagControls() method in Opponents.cs under the Assets/Scripts/Controllers directory, you will see some pieces of code like this
```
if (Input.GetKeyDown(KeyCode.Alpha3)){
    if (character.GetComponent<Ken>() != null){
        if (animator.GetBool ("isAttacking") == false) {
            character.AttackState ();
            animator.Play ("KenShinryuken", 0);
        }
        animator.SetTrigger ("motionSuperInputed");
    }
}
```

you change the KeyCode.Alpha3, which means press 3 on your normal keyboard and not your numpad, to whatever key you want. then you can execute the special like this shinryuken super by pressing 1 button instead.

afterwards, you go back to Player.cs script in the Assets/Scripts/Controllers/ directory and you paste this block of code underneath the attack input block of code like this.

```
void AttacksInput(){	
    //big blocks of command code
   if (Input.GetKeyDown(KeyCode.Alpha3)){
        if (character.GetComponent<Ken>() != null){
            if (animator.GetBool ("isAttacking") == false) {
                character.AttackState ();
                animator.Play ("KenShinryuken", 0);
            }
            animator.SetTrigger ("motionSuperInputed");
        }
    }
}
```

you must have `if (character.GetComponent<Ken>() != null)` if statement as it will exclusively check for which character the player is controlling. without this, if for say you choose sagat and you do indeed press alpha3, he'll do a wonky shinryuken animation and wont do anything with the attack.
so that if statement locks it in that ken and only ken can execute that sequence of command.

**Comment by stickylabdev** [comment]
thanks sir , but everyting is work fine now , even i can add mobile input ,yeah ,thanks
